name: Build Win32 versions on release
on: [push, pull_request, release, workflow_dispatch]
jobs:
  build_and_preview:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Build Nyrna portable
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows

          move build\windows\runner\Release build\Nyrna

          copy VERSION build\Nyrna
          xcopy C:\Windows\System32\msvcp140.dll build\Nyrna
          xcopy C:\Windows\System32\vcruntime140.dll build\Nyrna
          xcopy C:\Windows\System32\vcruntime140_1.dll build\Nyrna
      - name: Package with Inno Setup
        run: |
          iscc packaging\win32\inno_setup_script.iss
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-windows-portable
          path: build\Nyrna
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-windows-installer
          path: build\nyrna-windows-installer.exe
