name: Build AppImage on new release
on: [release, workflow_dispatch]
jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - name: Build Flutter app
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO:
          gh-releases-zsync|merrit|nyrna|latest|*x86_64.AppImage.zsync
        with:
          recipe: packaging/linux/appimage/AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
