name: Check Linux build succeeds on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-linux
          path: build/linux/release/bundle
