name: Check Microsoft Windows build succeeds on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@master
        with:
          name: windows
          path: build\windows\runner\Release
