name: Flutter test on Merge
'on':
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      - run: flutter config --enable-linux-desktop
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build linux
