name: Run unit tests
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: Enable Flutter desktop
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-windows-desktop
      - name: Get dependencies
        run: flutter pub get
      - name: Test native_platform
        run: |
          cd packages/native_platform
          dart run test
